### ISSUE TITLE
tag with OpenShift version

### ISSUE THREAD

**Issue by tmds** [redhat-developer/dotnet-jenkins-slave#14]
`dotnet-jenkins-slave` uses `jenkins-slave-base-rhel7` as its base image.

The base image contains `oc` binaries. These binaries should match the OpenShift installation. The base image is tagged with OpenShift versions (e.g. v3.9).

We should adopt the same tagging scheme.

See discussion at https://github.com/openshift/jenkins/issues/626 for more info.

CC @omajid @aslicerh @jerboaa

**Comment by aslicerh** [comment]
How do we want to format these labels? If we go with the example given in the jenkins slave discussion, they just used `v3.9`, which would make our tag `dotnet/dotnet-20-jenkins-slave-rhel7:v3.9`. I have some concern that it might be a little confusing.

Also, how many versions do we want to support? We can handle that with branches (either here or downstream), but each one will need their own dockerfile, plus a tags file for the build system.

**Comment by tmds** [comment]
> How do we want to format these labels? If we go with the example given in the jenkins slave discussion, they just used v3.9, which would make our tag dotnet/dotnet-20-jenkins-slave-rhel7:v3.9. I have some concern that it might be a little confusing.

We should follow upstream convention, unless we have a better idea.

> Also, how many versions do we want to support? We can handle that with branches (either here or downstream), but each one will need their own dockerfile, plus a tags file for the build system.

Proposal:
- With each .NET Core x.y release, we have an initial tag on a new image
- With the May-ish .NET Core release, we add an additional tag for each supported LTS release

In both cases, we match what is then the latest tag on the base image.

In practice, that means we'll have 1 tag for each Current release, and for each LTS release a tag which is at most about a year out-of-sync with OpenShift version.
wdyt?

**Comment by aslicerh** [comment]
> In both cases, we match what is then the latest tag on the base image.

By `latest`, do you mean what they have tagged with the `latest` tag (which is actually an old version by design), or the newest version? If the latter, what about when they change minor or major versions (like the soon-to-be shift from 3.9 to 3.10)?

**Comment by tmds** [comment]
> By latest, do you mean what they have tagged with the latest tag (which is actually an old version by design), or the newest version? If the latter, what about when they change minor or major versions (like the soon-to-be shift from 3.9 to 3.10)?

The latter. Currently `latest` on `jenkins-slave-base-rhel7` points to `v3.6` and the newest version is `v3.9`. So our 2.1 release would be `dotnet/dotnet-21-jenkins-slave-rhel7:v3.9` and when we refresh LTS in about a year, it will be `dotnet/dotnet-20-jenkins-slave-rhel7:v3.13`  (assuming `v3.13` is latest then).
I think OpenShift keeps `latest` at 3.6 due to the breaking change in 3.7 mentioned by Ben. We should keep it fixed at its current version too. When we do another slave image (2.2) we shouldn't add a `latest`.

**Comment by aslicerh** [comment]
So once we choose a jenkins slave version to tag, we will only use that version in that image, or is there an upgrade path?

> When we do another slave image (2.2) we shouldn't add a latest.

By this, do you mean that for dotnet-22-jenkins-slave-rhel7 should have no latest tag at all?

**Comment by tmds** [comment]
> So once we choose a jenkins slave version to tag, we will only use that version in that image, or is there an upgrade path?

Yes. If it is tagged v3.9, it is based on slave v3.9. We can't change that later.
If at LTS renew we add a v3.13, at that point we'll maintain both the v3.9 and v3.13 based on their respective slave tags.

> By this, do you mean that for dotnet-22-jenkins-slave-rhel7 should have no latest tag at all?

I think that makes sense. If someone is using latest and we update it to become another tag, we can break their build.
So we shouldn't have a latest. Or if we have one, we should keep it on the first tag. (The jenkins slave latest moved as long as it was backwards compatible.)

**Comment by tmds** [comment]
@aslicerh as discussed

The support policy of the base image is changing to support the latest and previous two versions.

Updated proposal:

For each .NET Core version (e.g. 2.0, 2.1) we'll support a single tag until the version is EOL.
When a new version of .NET Core is available, we'll use the latest base image version.
When support for a base image version is dropped, we'll move any .NET Core Jenkins image based on that version to the latest base image version.

This means we'll be skipping per 2 versions (e.g. moving from base 3.7 to 3.10).

**Comment by aslicerh** [comment]
@tmds I think that makes a lot of sense, and I can agree with that. Do we need to declare that somewhere here in the readme, or in an SLA file or something?

**Comment by tmds** [comment]
Yes, we'll write it up in the readme.

**Comment by tmds** [comment]
Closing, since no one has requested this.
