### ISSUE TITLE
Where are the images ready to be pulled?

### ISSUE THREAD

**Issue by hiredgunhouse** [redhat-developer/dotnet-jenkins-slave#21]
I tried searching on quay.io but it's just impossible to find anything there.
Where can I pull the images from? Also it would be nice to have templates to easily import them into OpenShift.

**Comment by hiredgunhouse** [comment]
I think I found it.
https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/dotnet/dotnet-22-jenkins-slave-rhel7

**Comment by tmds** [comment]
hi @hiredgunhouse I hadn't noticed this issue. Yes, all published images can be found in the registry.
