### ISSUE TITLE
curl's certificate verify locations on dotnet-30-jenkins-slave-rhel7 seems wrong

### ISSUE THREAD

**Issue by eitchugo** [redhat-developer/dotnet-jenkins-slave#24]
When using the `dotnet-30-jenkins-slave-rhel7` image, curl is trying to get the system's CA files from the SCL root, and it doesn't exist:

```
$ curl -v https://github.com
curl: (77) error setting certificate verify locations:
  CAfile: /opt/rh/rh-dotnet30/root/etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```

The error does not happen when using `dotnet-22-jenkins-slave-rhel7`:

```
$ curl -v https://github.com
[...]
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
[...]
```

This causes a jenkins to fail while trying to checkout an external repository.

Current found workaround is to set environment variable before running the build:

```
export CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
```

Let me know if you need more information.

**Comment by omajid** [comment]
Thanks for reporting this. This is also tracked at https://bugzilla.redhat.com/show_bug.cgi?id=1768029

**Comment by tmds** [comment]
This has been fixed in the rpms.
