### ISSUE TITLE
Create CentOS mirror image

### ISSUE THREAD

**Issue by jerboaa** [redhat-developer/dotnet-jenkins-slave#3]
Similar to https://github.com/redhat-developer/s2i-dotnetcore/issues/36 but for the jenkins slave. Once it's available, [configuration in openshift/jenkins](https://github.com/openshift/jenkins/pull/371) should get updated to use the centos-based slave for non-RHEL.

**Comment by jerboaa** [comment]
@omajid @aslicerh FYI.

**Comment by tmds** [comment]
@jerboaa shall I do the PR for centos index next?

**Comment by jerboaa** [comment]
@tmds yes, but you are going to need a cccp.yml in this repo first. I'd go with adding that one then do the index, wait for the image to get pushed and finally do the jenkins config update.

**Comment by tmds** [comment]
Implemented in
https://github.com/redhat-developer/dotnet-jenkins-slave/pull/5: Dockerfile
https://github.com/CentOS/container-index/pull/216: registry.centos.org image
https://github.com/openshift/jenkins/pull/405: openshift jenkins slave config

**Comment by jerboaa** [comment]
Nice work!
